### ISSUE TITLE
yaml support

### ISSUE THREAD

**Issue by jdorfman** [stickermule/rump#5]
I wonder if it would make sense to have support for `yaml` config's. That way you could do: 
```
$ rump -bookmark local
$ rump -b prod
```

`_config.yml`:
```yaml
bookmark:
  local:
    from: 'redis://127.0.0.1:6379/1'
    to: 'redis://127.0.0.1:6379/2'
  prod:
    from: 'redis://production.cache.amazonaws.com:6379/1'
    to: 'redis://127.0.0.1:6379/1'
```
